# (C) 2021 Fred Boniface, distributed under the GPLv3 License, a copy of which
# is included with this software.

checks:
    secondsinterval: 60  # Default to 120
    reportHttpStatus: True # Default to TRUE

output:
    enableJSON: True  # Default to FALSE
    hideDomainInJSON: True  # Default to FALSE
    webroot: '/var/www/git/alive.fb-infra.uk'
    email: True  # Default to FALSE
    address: 'fred@fjla.uk'
    telegram: False  # Default to FALSE
    number: ''

# List the domains to test below, and the unique test to search for in the
# response.  This could be the <title> of the page or a specific header.
# if you do not want to include a unique test, leave it blank eg.
#    'https://example.com': '<title>Exemplar</title>'
#
# Alive-Checker supports HTTP, HTTPS and LDAPS endpoints.  It does not support
# self-signed HTTP certificates at this point.

testDomains:
    'https://music.fjla.uk': '<title>Airsonic</title>'
    'https://jf.fjla.uk': '<title>Jellyfin</title'
    'https://nc.fjla.uk': '<title>Nextcloud</title>'
